[book]
authors = ["Portail contributors"]
language = "en"
src = "../src/en"
title = "Portail Documentation"

[output.html]
theme = "../theme"
site-url = "/portail/docs/en/"
git-repository-url = "https://github.com/cloud-gouv/portail"
edit-url-template = "https://github.com/cloud-gouv/portail/edit/main/docs/src/en/{path}"

[output.html.print]
enable = true

[output.html.fold]
enable = true
level = 2
