[package]
name = "portail"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"

[lints.clippy]
enum_variant_names = "allow"
undocumented_unsafe_blocks = "deny"

[dependencies]
annotate-snippets = "^0.12"
anyhow = "^1"
bytes = "^1"
clap = { version = "^4", features = ["derive", "string"] }
fast-socks5 = "^1"
http = "^1"
http-body-util = "^0.1"
hyper = { version = "^1", features = ["server", "client", "http1", "http2"] }
hyper-util = { version = "^0.1", features = ["tokio", "server", "http1"] }
nix = { version = "^0.31", features = ["socket", "uio", "net", "resource", "user"] }
regex = "^1"
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
serde_with = "^3"
thiserror = "^2"
tokio = { version = "^1", features = ["rt-multi-thread", "net", "io-util", "time", "sync", "macros", "signal"] }
tokio-rustls = "^0.26"
toml = "^1"
tracing = "^0.1"
tracing-subscriber = { version = "^0.3", features = ["env-filter", "json", "std"] }
winnow = "^1"
zlink = "^0.7"
rustls-pki-types = "^1"
uuid = { version = "^1", features = ["v4"] }
tracing-appender = "0.2.5"
hickory-resolver = { version = "^0.26", features = ["tokio"] }
futures = "0.3.33"
tokio-util = "0.7.19"

[dev-dependencies]
criterion = { version = "=0.8.2", features = ["html_reports"] }
insta = "=1.48.0"
rand = "=0.10.2"

[[bench]]
name = "acl"
harness = false

[profile.dev.package]
insta.opt-level = 3

[profile.release]
strip = "symbols"
lto = true
panic = "abort"
codegen-units = 1
