//! (Partially) generated code for Varlink interface `fr.gouv.portail.control`.
//!
//! This code was generated by `zlink-codegen` from Varlink IDL.
//! It was adapted for our needs.

use serde::{Deserialize, Serialize};
use std::{
    error::Error,
    fmt::Display,
    net::{AddrParseError, SocketAddr},
};
use thiserror::Error;
use tokio_rustls::rustls::pki_types::InvalidDnsNameError;
use zlink::{ReplyError, proxy};

use crate::config::KnownBackend;

#[derive(Debug, Clone, PartialEq, ReplyError, zlink::introspect::ReplyError)]
#[zlink(interface = "fr.gouv.portail.Control")]
pub enum ControlError {
    BackendNotFound {
        provided_backend: String,
        available_backends: Vec<String>,
    },
    /// Backend has invalid values (target address, TLS server names or something else.)
    InvalidBackend {
        reason: String,
    },
    PermissionDenied,
}

impl Display for ControlError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::BackendNotFound {
                provided_backend,
                available_backends,
            } => {
                f.write_fmt(format_args!(
                    "Backend `{}` was not found, available backends are {}",
                    provided_backend,
                    available_backends
                        .iter()
                        .map(|s| format!("`{}`", s))
                        .collect::<Vec<_>>()
                        .join(", ")
                ))?;
            }

            Self::PermissionDenied => {
                f.write_str("Permission was denied, are you in the authorized group?")?
            }

            Self::InvalidBackend { reason } => {
                f.write_fmt(format_args!("Backend passed had invalid data: {}", reason))?
            }
        }

        Ok(())
    }
}

impl Error for ControlError {}

/// Proxy trait for calling methods on the interface.
#[proxy("fr.gouv.portail.Control")]
pub trait Control {
    async fn set_default_backend(
        &mut self,
        backend_id: Option<&str>,
    ) -> zlink::Result<Result<(), ControlError>>;
    async fn get_current_backend(
        &mut self,
    ) -> zlink::Result<Result<GetCurrentBackendOutput, ControlError>>;
    async fn list_backends(&mut self) -> zlink::Result<Result<ListBackendsOutput, ControlError>>;
    async fn update_dynamic_backend(
        &mut self,
        backend_id: &str,
        backend_spec: DynamicBackendSpec,
    ) -> zlink::Result<Result<(), ControlError>>;
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, zlink::introspect::Type)]
pub struct DynamicBackendSpec {
    pub target_address: String,
    pub identity_aware: bool,
    pub tls_server_name: Option<String>,
}

#[derive(Debug, Error)]
pub enum DynamicBackendResolutionError {
    #[error("Invalid target address: {0}")]
    InvalidTargetAddress(#[from] AddrParseError),
    #[error("Invalid TLS server name: {0}")]
    InvalidServerName(#[from] InvalidDnsNameError),
}

impl TryFrom<DynamicBackendSpec> for KnownBackend {
    type Error = DynamicBackendResolutionError;

    fn try_from(value: DynamicBackendSpec) -> Result<Self, Self::Error> {
        let tgt_address: SocketAddr = value.target_address.parse()?;
        let ip = tgt_address.ip();
        Ok(Self {
            target_address: tgt_address,
            identity_aware: value.identity_aware,
            tls_server_name: match value.tls_server_name {
                Some(str) => str.try_into()?,
                None => ip.into(),
            },
        })
    }
}

impl From<DynamicBackendResolutionError> for ControlError {
    fn from(value: DynamicBackendResolutionError) -> Self {
        match value {
            DynamicBackendResolutionError::InvalidTargetAddress(err) => {
                ControlError::InvalidBackend {
                    reason: format!("Invalid target address: {}", err),
                }
            }
            DynamicBackendResolutionError::InvalidServerName(err) => ControlError::InvalidBackend {
                reason: format!("Invalid TLS server name: {}", err),
            },
        }
    }
}

/// Output parameters for the GetCurrentBackend method.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, zlink::introspect::Type)]
pub struct GetCurrentBackendOutput {
    pub backend_id: String,
}

/// A known backend specification.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, zlink::introspect::Type)]
pub struct KnownBackendSpec {
    pub target_address: String,
    pub identity_aware: bool,
    pub tls_server_name: String,
}

impl From<KnownBackend> for KnownBackendSpec {
    fn from(value: KnownBackend) -> Self {
        Self {
            target_address: format!("{}", value.target_address),
            identity_aware: value.identity_aware,
            tls_server_name: value.tls_server_name.to_str().into_owned(),
        }
    }
}

/// Returned as part of ListBackends method.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, zlink::introspect::Type)]
pub struct BackendListItem {
    pub id: String,
    pub current: bool,
    pub dynamic: bool,
    pub spec: Option<KnownBackendSpec>,
}

/// Output parameters for the ListBackends method.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, zlink::introspect::Type)]
pub struct ListBackendsOutput {
    pub backends: Vec<BackendListItem>,
}
