//! (Partially) generated code for Varlink interface `fr.gouv.portail.control`.
//!
//! This code was generated by `zlink-codegen` from Varlink IDL.
//! It was adapted for our needs.

use serde::{Deserialize, Serialize};
use std::{error::Error, fmt::Display};
use zlink::{proxy, ReplyError};

#[derive(Debug, Clone, PartialEq, ReplyError, zlink::introspect::ReplyError)]
#[zlink(interface = "fr.gouv.portail.Control")]
pub enum ControlError {
    BackendNotFound {
        provided_backend: String,
        available_backends: Vec<String>,
    },
    PermissionDenied,
}

impl Display for ControlError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::BackendNotFound {
                provided_backend,
                available_backends,
            } => {
                f.write_fmt(format_args!(
                    "Backend `{}` was not found, available backends are {}",
                    provided_backend,
                    available_backends
                        .into_iter()
                        .map(|s| format!("`{}`", s))
                        .collect::<Vec<_>>()
                        .join(", ")
                ))?;
            }

            Self::PermissionDenied => {
                f.write_str("Permission was denied, are you in the trusted group?")?
            }
        }

        Ok(())
    }
}

impl Error for ControlError {}

/// Proxy trait for calling methods on the interface.
#[proxy("fr.gouv.portail.Control")]
pub trait Control {
    async fn set_default_backend(
        &mut self,
        backend_id: &str,
    ) -> zlink::Result<Result<(), ControlError>>;
    async fn get_current_backend(
        &mut self,
    ) -> zlink::Result<Result<GetCurrentBackendOutput, ControlError>>;
}

/// Output parameters for the GetCurrentBackend method.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct GetCurrentBackendOutput {
    pub backend_id: String,
}
