filter-acl-rules-path = "./filter.acl"
# Timeouts (all in seconds, defaults shown)
# handshake-timeout = 15  # Time before the initial bytes are sent.
connect-timeout = 5 # TCP connect to backend/origin (was request-timeout)
tcp_nodelay = false

[backends.par01a]
target-address = "127.0.0.2:8000"
identity-aware = true
tls-server-name = "proxy.example.com"

[backends.par01b]
target-address = "127.0.0.2:8001"

[backends.par02a]
target-address = "127.0.0.2:8002"
identity-aware = true

[listener]
cacert-file = "./cacert.pem"
tls-privkey = "./server.key"
tls-chain = "./fullchain.pem"

[escaper]
cacert-file = "./cacert.pem"
tls-privkey = "./client.key"
tls-certificate = "./client.pem"

[dns]
# timeout = 5 # DNS resolution
