pub fn init() {
    let locale = std::env::var("LANG")
        .or_else(|_| std::env::var("LC_MESSAGES"))
        .unwrap_or_default();

    let lang = locale.split_once('.').map_or(locale.as_str(), |(l, _)| l);
    translators::set_locale(lang);
}

// Generated by build.rs
include!(concat!(env!("OUT_DIR"), "/locale/translators.rs"));
