jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - uses: samueldr/lix-gha-installer-action@7b7f14d320d6aacfb65bd1ef761566b3b69e474c # main
    - name: Build package
      run: nix-build ./nix -A package -I nixpkgs=channel:nixos-unstable
    - name: Build tests
      run: nix-build ./nix -A tests -I nixpkgs=channel:nixos-unstable
name: '[Portail] Run test suite'
on:
  pull_request:
  push:
    branches:
    - main
